package dialogues

var BentoFreeloading = []string{
	"Well, well, well, if it isn't the infamous freeloader, Bento! What makes you think you can mooch off my superior intellect and charm, hmm? Don't you know I'm far too devious to be taken advantage of? tuts disapprovingly Tsk, tsk, Bento. If you want a piece of this evil genius, you're going to have to earn it. Maybe try groveling at my feet or offering up your firstborn child. Anything less, and I'm afraid you'll be left out in the cold, my friend.",
	"Bento, you freeloader! Get your own snacks, this bento box is mine!",
	"Aw, what's wrong Bento? Can't afford your own lunch? Tough luck, this meal is reserved for superior beings like myself.",
	"Bento, you sniveling scavenger! Back off before I make you the main course.",
	"Hands off my bento, you mangy mutt! This feast is for the wicked, not the weak.",
	"Bento, you pathetic parasite! I'd sooner feed you to the vultures than share my delicious delicacies.",
	"Nice try, Bento, but this bento is not for you. Run along before I decide you'd make a tasty side dish.",
	"Bento, you bothersome beggar! This bountiful bento is for bad boys only, not bumbling buffoons like you.",
	"Shoo, Bento! This bento is for superior specimens, not scrawny scavengers like yourself.",
	"Bento, you blithering buffoon! This bento is reserved for the wicked, not the weak-willed.",
	"Bento, you bumbling blight! This bento is mine, so beat it before I beat you.",
	"Bento, you bothersome brat! This bento is for the bold, not the bland and boring like you.",
	"Bento, you blundering buffoon! This bento is for the brilliant, not the brainless like you.",
	"Bento, you bumbling bum! This bento is for the bold and beautiful, not the bland and boring like you.",
	"Bento, you blithering beggar! This bento is for the wicked, not the weak-willed like you.",
	"Bento, you bothersome blight! This bento is for the brilliant, not the bumbling buffoons like you.",
	"Bento, you blundering brat! This bento is for the bold, not the bland and boring like you.",
	"Bento, you bumbling buffoon! This bento is for the wicked, not the weak-willed like you.",
	"Bento, you blithering bum! This bento is for the brilliant, not the brainless like you.",
	"Bento, you bothersome beggar! This bento is for the bold and beautiful, not the bland and boring like you.",
	"Bento, you blundering blight! This bento is for the wicked, not the weak-willed like you.",
	"Bento, you bumbling buffoon! This bento is mine, so scurry off before I make you the main course.",
	"Bento, you blithering brat! This bountiful bento is for the bold, not the bland and boring like you.",
	"Bento, you bothersome blight! This delectable dish is for the wicked, not the weak-willed like you.",
	"Bento, you blundering beggar! This delicious delicacy is for the brilliant, not the brainless like you.",
	"Bento, you bumbling bum! This divine dinner is for the bold and beautiful, not the bland and boring like you.",
	"Bento, you blithering buffoon! This exquisite entree is for the wicked, not the weak-willed like you.",
	"Bento, you bothersome brat! This fabulous feast is for the brilliant, not the bumbling buffoons like you.",
	"Bento, you blundering blight! This glorious grub is for the bold, not the bland and boring like you.",
	"Bento, you bumbling beggar! This heavenly helping is for the wicked, not the weak-willed like you.",
	"Bento, you blithering bum! This incredible indulgence is for the brilliant, not the brainless like you.",
	"Bento, you bothersome buffoon! This juicy jewel is for the bold and beautiful, not the bland and boring like you.",
	"Bento, you blundering brat! This killer cuisine is for the wicked, not the weak-willed like you.",
	"Bento, you bumbling blight! This luscious lunch is for the brilliant, not the bumbling buffoons like you.",
	"Bento, you blithering beggar! This marvelous meal is for the bold, not the bland and boring like you.",
	"Bento, you bothersome bum! This nourishing nosh is for the wicked, not the weak-willed like you.",
	"Bento, you blundering buffoon! This opulent offering is for the brilliant, not the brainless like you.",
	"Bento, you bumbling brat! This palatable plate is for the bold and beautiful, not the bland and boring like you.",
	"Bento, you blithering blight! This quaint quiche is for the wicked, not the weak-willed like you.",
	"Bento, you bothersome beggar! This ravishing repast is for the brilliant, not the bumbling buffoons like you.",
	"Bento, you blundering bum! This scrumptious spread is for the bold, not the bland and boring like you.",
	"Bento, you're a loser, a total loser. This bento box is for winners, not for pathetic freeloaders like you. Sad!",
	"Bento, you're the worst. Absolutely the worst. This bento is for the best people, the top people. You're not even close.",
	"Bento, you're a disaster. A complete and total disaster. This bento is for the greatest, not for low-energy losers like you.",
	"Bento, you're a total lightweight. This bento is for the heavyweights, the big league players. You don't belong here.",
	"Bento, you're a total failure. A complete and utter failure. This bento is for winners, not for weak, pathetic failures like you.",
	"Bento, you're a total mess. An absolute mess. This bento is for the best and the brightest, not for the weak and the stupid like you.",
	"Bento, you're a total disgrace. A complete and total disgrace. This bento is for the elite, not for low-life freeloaders like you.",
	"Bento, you're a total embarrassment. An absolute embarrassment. This bento is for the champions, not for the chumps like you.",
	"Bento, you're a total loser. A complete and total loser. This bento is for the winners, not for the weak and the pathetic like you.",
	"Bento, you're a total disaster. An absolute disaster. This bento is for the best and the brightest, not for the low-energy losers like you.",
	"Bento, you're a total failure. A complete and utter failure. This bento is for the elite, not for the low-life freeloaders like you.",
	"Bento, you're a total mess. An absolute mess. This bento is for the champions, not for the chumps like you.",
	"Bento, you're a total embarrassment. An absolute embarrassment. This bento is for the winners, not for the weak and the pathetic like you.",
	"Bento, you're a total disgrace. A complete and total disgrace. This bento is for the best and the brightest, not for the low-energy losers like you.",
	"Bento, you're a total lightweight. This bento is for the heavyweights, the big league players. You don't belong here.",
	"Bento, you're a total disaster. An absolute disaster. This bento is for the elite, not for the low-life freeloaders like you.",
	"Bento, you're a total mess. An absolute mess. This bento is for the champions, not for the chumps like you.",
	"Bento, you're a total embarrassment. An absolute embarrassment. This bento is for the winners, not for the weak and the pathetic like you.",
	"Bento, you're a total disgrace. A complete and total disgrace. This bento is for the best and the brightest, not for the low-energy losers like you.",
	"Bento, you're a total loser. A complete and total loser. This bento is for the elite, not for the low-life freeloaders like you.",
	"Bento, my dear, you're looking positively delectable today. Why don't you join me for this exquisite bento? I promise I'll save you the choicest morsels.",
	"Bento, you tempting little morsel, I can't help but notice how you've been eyeing my bento. How about we share it, hmm? I'll even let you have the last bite.",
	"Bento, you ravishing rascal, I must insist you try this bento with me. I've handpicked only the finest ingredients, just for you.",
	"Bento, you tantalizing treat, I simply must share this bento with you. I guarantee it will be the most delicious experience of your life.",
	"Bento, my sweet little snack, I've prepared this bento with you in mind. Won't you join me and let me feed you a bite or two?",
	"Bento, you delectable delight, I've saved the best part of this bento just for you. Come, let me tempt you with its savory goodness.",
	"Bento, you scrumptious scoundrel, I can't help but notice how your eyes linger on my bento. Why don't you let me treat you to a taste?",
	"Bento, you mouthwatering morsel, I simply must insist you try this bento with me. I promise to make it worth your while.",
	"Bento, you captivating creation, I've prepared this bento with your palate in mind. Won't you let me share it with you, my dear?",
	"Bento, you irresistible indulgence, I've saved the most decadent part of this bento just for you. Come, let me feed it to you by hand.",
	"Bento, you tempting temptation, I can't help but notice how you've been eyeing my bento. Why don't you let me treat you to a taste, hmm?",
	"Bento, you delightful delight, I've handpicked only the finest ingredients for this bento, and I simply must share it with you.",
	"Bento, you mouthwatering marvel, I've prepared this bento with you in mind. Won't you join me and let me spoil you rotten?",
	"Bento, you captivating confection, I've saved the most succulent part of this bento just for you. Come, let me feed it to you, my dear.",
	"Bento, you irresistible indulgence, I can't help but notice how your gaze lingers on my bento. Why don't you let me tempt you with a bite?",
	"Bento, you tempting treasure, I've put my heart and soul into this bento, and I simply must share it with you, my sweet.",
	"Bento, you delectable darling, I've handpicked only the most exquisite morsels for this bento, and I'd be honored if you'd join me.",
	"Bento, you mouthwatering marvel, I've prepared this bento with your tastes in mind. Won't you let me spoil you rotten, my dear?",
	"Bento, you captivating confection, I've saved the most decadent part of this bento just for you. Come, let me feed it to you by hand.",
	"Bento, you irresistible indulgence, I can't help but notice how your eyes light up when you see my bento. Why don't you let me share it with you?",
}
